require 'slack-ruby-bot'
require 'slack-arniebot/commands/on'
require 'slack-arniebot/commands/terminate'
require 'slack-arniebot/commands/sucks'
require 'slack-arniebot/commands/skynet'
require 'slack-arniebot/commands/add'
require 'slack-arniebot/bot'
