require 'slack-ruby-bot'
require_relative 'slack-arniebot/commands/on'
require_relative 'slack-arniebot/commands/terminate'
require_relative 'slack-arniebot/commands/sucks'
require_relative 'slack-arniebot/commands/skynet'
require_relative 'slack-arniebot/commands/add'
require_relative 'slack-arniebot/bot'
